import crypto from 'crypto';

const ALGORITHM = 'aes-256-gcm';

// We require a 32-byte key for aes-256-gcm.
// In a real app, this comes from process.env.ENCRYPTION_KEY
// For this MVP, if it's missing or wrong length, we hash a fallback to ensure it's exactly 32 bytes.
const getEncryptionKey = (): Buffer => {
  const secret = process.env.ENCRYPTION_KEY || 'devpro-super-secret-encryption-key-fallback';
  return crypto.createHash('sha256').update(String(secret)).digest();
};

/**
 * Encrypts a plaintext string (like an access token)
 * Returns a composite string containing the iv, auth tag, and encrypted data
 * Format: iv:authTag:encryptedText
 */
export const encrypt = (text: string): string => {
  const iv = crypto.randomBytes(16);
  const key = getEncryptionKey();
  
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  const authTag = cipher.getAuthTag().toString('hex');
  
  return `${iv.toString('hex')}:${authTag}:${encrypted}`;
};

/**
 * Decrypts a composite string generated by the encrypt function
 */
export const decrypt = (encryptedData: string): string => {
  const parts = encryptedData.split(':');
  
  // If the data doesn't match our encrypted format, assume it's legacy plaintext
  if (parts.length !== 3) {
    return encryptedData;
  }
  
  const iv = Buffer.from(parts[0], 'hex');
  const authTag = Buffer.from(parts[1], 'hex');
  const encryptedText = parts[2];
  const key = getEncryptionKey();
  
  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);
  
  let decrypted = decipher.update(encryptedText, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  
  return decrypted;
};
